### ISSUE TITLE
'Write Story' popup; Title field flickers when user focus on another field

### ISSUE THREAD

**Issue by sdgun** [topcoderinc/va-online-memorial-frontend#20] opened 2018-06-21 20:38 UTC
## Target URL

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as a valid User [Normal]
3. Click Search button
4. Enter 'Branch of service' as US NAVY
5. Click 'Update Results' button
6. Click on any record > https://frontend.app.cloud.gov/dashboard/10
7. Click on 'Write Story'
8. Don't click on 'Title' field; Click on 'Message' field
9. Observe

## Actual Result(s)

- 'Write Story' popup; Title field flickers when user focus on another field

## Expected Result(s)

- Must not flicker the field when focusing on another field

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 67.0.3396.87 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/iRPR8Q75wrB

**Comment by sdgun** [comment] 2018-06-21 21:02
Same thing happens to Title field in 'Write Testimonial'

**Comment by ramillim** [comment] 2018-06-23 05:12
Unable to reproduce issue.

**Comment by ramillim** [comment] 2018-07-02 15:52
@dustinWeaver This one needs a retest label since I could not reproduce it.

**Comment by dustinWeaver** [comment] 2018-07-02 15:55
@ksmacleod99, can you retest this one when you get a chance?  If it's OK, then let's close it.

**Comment by ksmacleod99** [comment] 2018-07-08 14:54
I'm going to close this since I couldn't get it to reproduce either.

**Closed by ksmacleod99** 2018-07-08 14:54 UTC
Labels: bug, retest
