### ISSUE TITLE
[$50] ProfileCard Component needs refinement

### ISSUE THREAD

**Issue by ksmacleod99** [topcoderinc/va-online-memorial-frontend#97] opened 2018-07-30 20:02 UTC
the ProfileCard component is using the default.json data completely, so even if the profile has a profile photo, it doesn't get displayed because the placeholder is displayed

**Comment by dustinTopcoder** [comment] 2018-08-15 20:22
Dupe of #96

**Closed as completed by dustinTopcoder** 2018-08-15 20:22 UTC
Labels: duplicate

**Comment by dustinTopcoder** [comment] 2018-08-15 20:25
Contest https://www.topcoder.com/challenges/30069550 has been created for this ticket.

**Comment by dustinTopcoder** [comment] 2018-08-15 20:25
Contest https://www.topcoder.com/challenges/30069550 has been updated - the new changes has been updated for this ticket.
