### ISSUE TITLE
[$100] Search sometimes returns different results. 

### ISSUE THREAD

**Issue by AshTemp** [topcoderinc/va-online-memorial-frontend#117] opened 2018-08-15 20:45 UTC
## Target URL 

https://frontend.app.cloud.gov/dashboard/10

## Steps to Reproduce

1. Open the URL https://frontend.app.cloud.gov/
2. Login as any user.
3. Search for a person.
4. Wait a few minutes and search for that person again.

## Actual Result(s)
* Different results are displayed each time.

## Expected Result(s)
*  Same or at least similar results are displayed.

## Frequency
* 2/5

## Environment Details
* Device(s): Desktop
* Operating System: Windows 10 64bit
* Browser(s): Chrome 67.0.3396.99 (Official Build) (64-bit), Firefox 61.0.1 (64-bit)

**Comment by dustinTopcoder** [comment] 2018-08-15 21:42
Contest https://www.topcoder.com/challenges/30069559 has been created for this ticket.

**Comment by dustinTopcoder** [comment] 2018-08-15 21:43
Contest https://www.topcoder.com/challenges/30069559 has been updated - the new changes has been updated for this ticket.

**Comment by jiangliwu** [comment] 2018-08-31 13:25
@dustinTopcoder i test many times, cannot reproduce this, all worked as expected,
i guess someone update database when her test.
or can you provide more details ?

**Comment by dustinTopcoder** [comment] 2018-09-04 17:54
I think this was previous due to the timing of the search results back to the front end.  For now, with my testing as well, it doesn't seem to be an issue anymore.  As such, I'll close it.

**Closed as completed by dustinTopcoder** 2018-09-04 17:54 UTC
Labels: Priority 1
